#include "CaptureStrategy.h"
#include "screen/AreaSelector.h"
#include "screen/SelectorGroup.h"
#include "capture/CaptureGeometry.h"
#include "capture/OverlayAnnotations.h"
#include "core/FileNames.h"
#include "core/Settings.h"
#include "screen/sources/DesktopFrameSource.h"

#include <QClipboard>
#include <QDateTime>
#include <QDebug>
#include <QDir>
#include <QFileDialog>
#include <QGuiApplication>

namespace Capture {

// This file provides the implementation for the CaptureStrategy base class
// The signals are automatically generated by Qt's MOC system

QPixmap CaptureStrategy::cropWithAnnotations(const QPixmap &shot, const QRect &virtualGeometry,
                                             const QRect &area,
                                             const QSharedPointer<OverlayAnnotations> &annotations)
{
    if (annotations && annotations->hasItems())
        return annotations->flattenedCrop(area);
    return cropVirtualArea(shot, virtualGeometry, area);
}

void CaptureStrategy::emitSelection(const QPixmap &shot, const QRect &virtualGeometry,
                                    const QRect &area,
                                    const QSharedPointer<OverlayAnnotations> &annotations)
{
    const QPixmap cropped = cropVirtualArea(shot, virtualGeometry, area);
    if (cropped.isNull()) {
        emit screenshotFailed("Invalid area selected or no screenshot available");
        return;
    }
    emit screenshotReady(cropped, annotations && annotations->hasItems()
                                      ? annotations->snapshot(area) : Editor::AnnotationSet{});
}

QSharedPointer<OverlayAnnotations> CaptureStrategy::attachAnnotations(
    const QList<Screen::AreaSelector*> &selectors, const QPixmap &frame, const QRect &virtualGeometry)
{
    if (!quickActionsEnabled())
        return {};
    // deleteLater: the last reference can drop inside one of the session's own signals.
    QSharedPointer<OverlayAnnotations> session(new OverlayAnnotations(frame, virtualGeometry),
                                               &QObject::deleteLater);
    for (Screen::AreaSelector *selector : selectors)
        selector->setLayer(session);
    return session;
}

void CaptureStrategy::showAreaSelector(const QPixmap &frame, const QRect &virtualGeometry)
{
    qDebug() << "Showing area selector, virtual geometry:" << virtualGeometry
             << "frame:" << frame.size() << "DPR:" << frame.devicePixelRatio();

    Screen::SelectorGroup::Options options;
    options.actions = quickActionsEnabled();
    auto *group = new Screen::SelectorGroup(frame, virtualGeometry, options, this);
    const auto annotations = attachAnnotations(group->selectors(), frame, virtualGeometry);

    // The group closes every overlay before it signals, so the save dialog is never covered.
    connect(group, &Screen::SelectorGroup::areaSelected, this,
            [this, frame, virtualGeometry, annotations](const QRect &area) {
        if (area.isEmpty()) {
            qDebug() << "Area selection cancelled";
            emit screenshotCancelled();
            return;
        }
        emitSelection(frame, virtualGeometry, area, annotations);
    });
    connect(group, &Screen::SelectorGroup::copyRequested, this,
            [this, frame, virtualGeometry, annotations](const QRect &area) {
        copyAreaToClipboard(frame, virtualGeometry, area, annotations);
    });
    connect(group, &Screen::SelectorGroup::saveRequested, this,
            [this, frame, virtualGeometry, annotations](const QRect &area) {
        saveAreaToFile(frame, virtualGeometry, area, annotations);
    });
}

void CaptureStrategy::deliverFrame(const QPixmap &frame, const QRect &virtualGeometry,
                                   bool showSelector)
{
    if (!Screen::frameCoversGeometry(frame.size(), frame.devicePixelRatio(), virtualGeometry)) {
        qInfo() << "Capture: the frame" << frame.size() << "covers only part of" << virtualGeometry
                << "so it is taken as it is";
        emit screenshotReady(frame);
        return;
    }
    if (showSelector)
        showAreaSelector(frame, virtualGeometry);
    else
        emit screenshotReady(frame);
}

void CaptureStrategy::tearDownSelectors(QList<Screen::AreaSelector*> *selectors)
{
    for (auto *selector : *selectors) {
        selector->blockSignals(true);
        selector->disconnect();
        selector->close();
        selector->deleteLater();
    }
    delete selectors;
}

void CaptureStrategy::copyAreaToClipboard(const QPixmap &shot, const QRect &virtualGeometry,
                                          const QRect &area,
                                          const QSharedPointer<OverlayAnnotations> &annotations)
{
    const QPixmap cropped = cropWithAnnotations(shot, virtualGeometry, area, annotations);
    if (cropped.isNull())
        return;

    QGuiApplication::clipboard()->setPixmap(cropped);
    qDebug() << "Selection copied to clipboard:" << cropped.size();
}

void CaptureStrategy::saveAreaToFile(const QPixmap &shot, const QRect &virtualGeometry,
                                     const QRect &area,
                                     const QSharedPointer<OverlayAnnotations> &annotations)
{
    const QPixmap cropped = cropWithAnnotations(shot, virtualGeometry, area, annotations);
    if (cropped.isNull())
        return;

    // The overlay is already torn down, so this dialog isn't hidden behind it.
    const QString dir = Core::Settings::screenshotFolder();
    QDir().mkpath(dir);
    const QString fileName = QFileDialog::getSaveFileName(
        nullptr, "Save Screenshot",
        dir + "/" + Core::screenshotFileName(QDateTime::currentDateTime(),
                                             Core::Settings::imageFormat()),
        "Image Files (*.png *.jpg *.bmp)");
    if (!fileName.isEmpty())
        cropped.save(fileName);
}

} // namespace Capture
