#include "CaptureStrategy.h"
#include "screen/AreaSelector.h"
#include "capture/CaptureGeometry.h"
#include "capture/OverlayAnnotations.h"
#include "core/FileNames.h"
#include "core/Settings.h"

#include <QClipboard>
#include <QDateTime>
#include <QDebug>
#include <QDir>
#include <QFileDialog>
#include <QGuiApplication>

namespace Capture {

// This file provides the implementation for the CaptureStrategy base class
// The signals are automatically generated by Qt's MOC system

QPixmap CaptureStrategy::cropWithAnnotations(const QPixmap &shot, const QRect &virtualGeometry,
                                             const QRect &area,
                                             const QSharedPointer<OverlayAnnotations> &annotations)
{
    if (annotations && annotations->hasItems())
        return annotations->flattenedCrop(area);
    return cropVirtualArea(shot, virtualGeometry, area);
}

void CaptureStrategy::emitSelection(const QPixmap &shot, const QRect &virtualGeometry,
                                    const QRect &area,
                                    const QSharedPointer<OverlayAnnotations> &annotations)
{
    const QPixmap cropped = cropVirtualArea(shot, virtualGeometry, area);
    if (cropped.isNull()) {
        emit screenshotFailed("Invalid area selected or no screenshot available");
        return;
    }
    emit screenshotReady(cropped, annotations && annotations->hasItems()
                                      ? annotations->snapshot(area) : Editor::AnnotationSet{});
}

QSharedPointer<OverlayAnnotations> CaptureStrategy::attachAnnotations(
    const QList<Screen::AreaSelector*> &selectors, const QPixmap &frame, const QRect &virtualGeometry)
{
    if (!quickActionsEnabled())
        return {};
    // deleteLater: the last reference can drop inside one of the session's own signals.
    QSharedPointer<OverlayAnnotations> session(new OverlayAnnotations(frame, virtualGeometry),
                                               &QObject::deleteLater);
    for (Screen::AreaSelector *selector : selectors)
        selector->setLayer(session);
    return session;
}

void CaptureStrategy::copyAreaToClipboard(const QPixmap &shot, const QRect &virtualGeometry,
                                          const QRect &area,
                                          const QSharedPointer<OverlayAnnotations> &annotations)
{
    const QPixmap cropped = cropWithAnnotations(shot, virtualGeometry, area, annotations);
    if (cropped.isNull())
        return;

    QGuiApplication::clipboard()->setPixmap(cropped);
    qDebug() << "Selection copied to clipboard:" << cropped.size();
}

void CaptureStrategy::saveAreaToFile(const QPixmap &shot, const QRect &virtualGeometry,
                                     const QRect &area,
                                     const QSharedPointer<OverlayAnnotations> &annotations)
{
    const QPixmap cropped = cropWithAnnotations(shot, virtualGeometry, area, annotations);
    if (cropped.isNull())
        return;

    // The overlay is already torn down, so this dialog isn't hidden behind it.
    const QString dir = Core::Settings::screenshotFolder();
    QDir().mkpath(dir);
    const QString fileName = QFileDialog::getSaveFileName(
        nullptr, "Save Screenshot",
        dir + "/" + Core::screenshotFileName(QDateTime::currentDateTime(),
                                             Core::Settings::imageFormat()),
        "Image Files (*.png *.jpg *.bmp)");
    if (!fileName.isEmpty())
        cropped.save(fileName);
}

} // namespace Capture
