#include "CaptureStrategy.h"

namespace Capture {

// This file provides the implementation for the CaptureStrategy base class
// The signals are automatically generated by Qt's MOC system

} // namespace Capture
